name: PHP CI

on: [push]

jobs:
  test:
    name: Test on PHP ${{ matrix.php-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php-version: ['7.2', '7.3']
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@master
    - uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}
    - run: composer install -n --prefer-dist
    - run: vendor/bin/phpunit
